import "./globals.css"
import { Roboto_Mono } from "next/font/google"

const roboto_mono = Roboto_Mono({ subsets: ["latin"] })

export const metadata = {
  title: "Next 13.4 Crud",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto_mono.className}>
        <main className="h-screen p-8 bg-slate-900 text-slate-200 grid place-items-center">
          {children}
        </main>
      </body>
    </html>
  )
}
